# Generated by Django 5.2.5 on 2025-09-12 00:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100, unique=True, verbose_name='カードの名前')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_card_image', models.ImageField(blank=True, null=True, upload_to='card_images/', verbose_name='カード画像')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100, unique=True, verbose_name='ゲームの名前')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_game_log', models.JSONField(blank=True, default=list, help_text='ゲームの操作履歴を [関数名, [引数のリスト], 誰からの指示か(User)、説明文、日時] の形式で保存します。', verbose_name='ゲームログ')),
                ('_field_cardID_data', models.JSONField(blank=True, default=dict, help_text='どこにどのカードがあるかを管理する辞書。', verbose_name='どの場所にどこカードがあるか')),
                ('_field_card_design_data', models.JSONField(default=dict, help_text='これは基本的に変更しない。HTMLに送るだけ。', verbose_name='各場所をどのように表示するか')),
                ('_cards', models.ManyToManyField(blank=True, related_name='game', to='game_factory.card', verbose_name='ゲーム内のカード一覧')),
                ('_players', models.ManyToManyField(blank=True, related_name='joined_games', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー')),
            ],
        ),
        migrations.CreateModel(
            name='GameDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100, unique=True, verbose_name='ゲームの名前')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_published', models.BooleanField(default=False, verbose_name='公開状態')),
                ('_player_limit', models.IntegerField(default=10, help_text='ゲームに参加できるプレイヤーの上限人数を設定します。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='プレイヤー上限')),
                ('_field_card_design_data', models.JSONField(default=dict, help_text='これは基本的に変更しない。HTMLに送るだけ。', verbose_name='各場所をどのように表示するか')),
                ('_cards', models.ManyToManyField(blank=True, related_name='gamedesign', to='game_factory.card', verbose_name='ゲーム内のカード一覧')),
                ('_creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_game_designs', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100, unique=True, verbose_name='部屋の名前')),
                ('_password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_status', models.CharField(choices=[('OPEN', '解放'), ('CLOSED', '締切')], default='OPEN', max_length=10, verbose_name='ステータス')),
                ('_game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_room', to='game_factory.game')),
                ('_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_game_rooms', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
                ('_playing_members', models.ManyToManyField(blank=True, related_name='joined_playing_game_rooms', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game_factory.room', verbose_name='部屋'),
        ),
    ]
