# Generated by Django 5.2.5 on 2025-09-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='_room',
        ),
    ]
