# Generated by Django 5.2.5 on 2025-09-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0002_remove_game__room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='_name',
            field=models.CharField(max_length=100, verbose_name='ゲームの名前'),
        ),
    ]
