# Generated by Django 5.2.5 on 2025-09-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0003_alter_game__name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_field_card_design_data',
            new_name='_field_card_design_dict',
        ),
        migrations.RenameField(
            model_name='gamedesign',
            old_name='_field_card_design_data',
            new_name='_field_card_design_dict',
        ),
    ]
