# Generated by Django 5.2.5 on 2025-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0004_rename__field_card_design_data_game__field_card_design_dict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedesign',
            name='_init_field_cardID_dict',
            field=models.JSONField(default=dict, verbose_name='初期で各カードがどのPublicFieldに存在するかの辞書'),
        ),
    ]
