# Generated by Django 5.2.5 on 2025-09-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0005_gamedesign__init_field_cardid_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_field_cardID_data',
            new_name='_field_cardID_dict',
        ),
    ]
