# Generated by Django 5.2.5 on 2025-09-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0006_rename__field_cardid_data_game__field_cardid_dict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedesign',
            old_name='_init_field_cardID_dict',
            new_name='_init_field_cardInfo_dict',
        ),
    ]
