# Generated by Django 5.2.5 on 2025-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0007_rename__init_field_cardid_dict_gamedesign__init_field_cardinfo_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='_name',
            field=models.CharField(max_length=100, verbose_name='カードの名前'),
        ),
    ]
