# Generated by Django 5.2.5 on 2025-09-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0008_alter_card__name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_field_cardID_dict',
            new_name='_field_cardInfo_dict',
        ),
    ]
