# Generated by Django 5.2.5 on 2025-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0009_rename__field_cardid_dict_game__field_cardinfo_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_fcs_for_user_dict',
            field=models.JSONField(blank=True, default=dict, verbose_name='Card一枚一枚のステータスを仮想フィールドごと、ユーザーごとに管理'),
        ),
        migrations.AlterField(
            model_name='game',
            name='_field_cardInfo_dict',
            field=models.JSONField(blank=True, default=dict, verbose_name='どの場所にどこカードがあるか'),
        ),
        migrations.AlterField(
            model_name='game',
            name='_field_card_design_dict',
            field=models.JSONField(default=dict, verbose_name='各仮想フィールドをどのように表示するか'),
        ),
    ]
