# Generated by Django 5.2.5 on 2025-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0010_game__fcs_for_user_dict_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_fcs_for_user_dict',
            new_name='_card_status_for_user_dict',
        ),
        migrations.AddField(
            model_name='game',
            name='_player_id_order',
            field=models.JSONField(blank=True, default=list, verbose_name='プレイヤーの順番を定義'),
        ),
    ]
