# Generated by Django 5.2.5 on 2026-06-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_factory', '0011_rename__fcs_for_user_dict_game__card_status_for_user_dict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_game_design_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='元のゲームデザインID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='_card_status_for_user_dict',
            field=models.JSONField(blank=True, default=dict, verbose_name='_card_status_for_user_dict:Card一枚一枚のステータスを仮想フィールドごと、ユーザーごとに管理'),
        ),
        migrations.AlterField(
            model_name='game',
            name='_field_cardInfo_dict',
            field=models.JSONField(blank=True, default=dict, verbose_name='_field_cardInfo_dict:どの場所にどこカードがあるか'),
        ),
        migrations.AlterField(
            model_name='game',
            name='_field_card_design_dict',
            field=models.JSONField(default=dict, verbose_name='_field_card_design_dict:各仮想フィールドをどのように表示するか'),
        ),
        migrations.AlterField(
            model_name='game',
            name='_player_id_order',
            field=models.JSONField(blank=True, default=list, verbose_name='_player_id_order'),
        ),
    ]
