# Generated by Django 3.1.3 on 2025-06-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100, unique=True, verbose_name='部屋の名前')),
                ('_password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('playing', '遊戯中'), ('closed', '退室')], default='waiting', max_length=20, verbose_name='部屋の状態')),
            ],
        ),
    ]
