# Generated by Django 3.1.3 on 2025-06-09 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UNO', '0002_auto_20250608_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='_members',
        ),
        migrations.AddField(
            model_name='room',
            name='_playing_members',
            field=models.ManyToManyField(blank=True, related_name='joined_playing_rooms', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー'),
        ),
        migrations.AddField(
            model_name='room',
            name='_waiting_members',
            field=models.ManyToManyField(blank=True, related_name='joined_waiting_rooms', to=settings.AUTH_USER_MODEL, verbose_name='参加メンバー'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', '待機中'), ('playing', '遊戯中'), ('closed', '退室')], default='closed', max_length=20, verbose_name='部屋の状態'),
        ),
    ]
