# Generated by Django 3.1.3 on 2025-06-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UNO', '0003_auto_20250609_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
