# Generated by Django 3.1.3 on 2025-06-14 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UNO', '0004_remove_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_player_order', models.JSONField(default=list, help_text='プレイヤーのIDを順番に格納したリスト', verbose_name='プレイヤーの順番')),
                ('_turn_player_index', models.PositiveIntegerField(default=0, verbose_name='現在どのプレイヤーターンかを示すインデックス')),
                ('_turn_direction', models.IntegerField(choices=[(1, '時計回り'), (-1, '反時計回り')], default=1, verbose_name='ターンの進行方向')),
                ('_current_turn_num', models.PositiveIntegerField(default=0, verbose_name='現在のターン数')),
                ('_action_que', models.JSONField(default=list, help_text='カードの効果などをここに蓄積して順番に実行する', verbose_name='アクションを保存するキュー')),
                ('_game_logger', models.JSONField(default=list, help_text="['turn=1,time=~~~,fanc=draw_card(deck,2),detail=player_a_draw_2_card_from_deck']", verbose_name='ゲーム進行のログを保存するリスト')),
                ('_place_and_card', models.JSONField(default=dict, help_text="どこにどのカードがあるかを管理するリスト。｛'place_name':[card1, card2...]｝形式", verbose_name='どこにどこカードがあるか')),
                ('_current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='現在のプレイヤー')),
                ('_room', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_game', to='UNO.room', verbose_name='部屋')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='色')),
                ('rank', models.CharField(max_length=20, verbose_name='種類/数字')),
                ('action', models.TextField(blank=True, verbose_name='カードの効果')),
            ],
            options={
                'unique_together': {('color', 'rank')},
            },
        ),
    ]
