# Generated by Django 3.1.3 on 2025-06-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UNO', '0005_card_gamemaster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
    ]
