# Generated by Django 3.1.3 on 2025-06-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNO', '0006_auto_20250614_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemaster',
            old_name='_player_order',
            new_name='_player_id_order',
        ),
        migrations.RemoveField(
            model_name='gamemaster',
            name='_place_and_card',
        ),
        migrations.AddField(
            model_name='gamemaster',
            name='_place_and_card_id',
            field=models.JSONField(default=dict, help_text="どこにどのカードがあるかを管理するリスト。｛'place_name':[card1.id, card2.id...]｝形式", verbose_name='どこにどこカードがあるか'),
        ),
    ]
