# Generated by Django 3.1.3 on 2025-06-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNO', '0007_auto_20250614_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemaster',
            name='_game_name',
            field=models.CharField(default='unknown_game', max_length=30, verbose_name='ゲーム名'),
        ),
    ]
