# Generated by Django 3.1.3 on 2025-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNO', '0008_gamemaster__game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamemaster',
            old_name='_place_and_card_id',
            new_name='_place_card_id_dict',
        ),
        migrations.AddField(
            model_name='gamemaster',
            name='_cards',
            field=models.ManyToManyField(blank=True, related_name='game_card', to='UNO.Card', verbose_name='ゲーム内のカード一覧'),
        ),
    ]
