# Generated by Django 5.2.5 on 2025-09-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNO', '0009_auto_20250614_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemaster',
            name='_game_logger',
            field=models.JSONField(default=list, help_text="['move_card_fromAtoB|card_id|placeA|placeB|プレイヤーAがカードXを場所Bに移動させました']のように関数名、引数名、説明文を入力する", verbose_name='ゲーム進行のログを保存するリスト'),
        ),
        migrations.AlterField(
            model_name='gamemaster',
            name='_place_card_id_dict',
            field=models.JSONField(default=dict, help_text="どこにどのカードがあるかを管理するリスト。｛'str(place_name)':[int(card1.id), int(card2.id)...]｝形式", verbose_name='どこにどこカードがあるか'),
        ),
    ]
